apiVersion: ifood/v2.5
kind: Repository
tags:
  - webapp
spec:
  contents:
    - name: vs-angular-qrcode
      description: Lib Frontend for generate QrCode
      type: service
      ownerLayerSlug: op-om-totem
      subType:
        - webapp
      impactLevel: 3
      deployment:
        type: k8s_helm
